"use client";
import {Plus,Trash2} from "lucide-react";
import type {SetEntry} from "@/db/schema/physical";
import {Button} from "@/components/ui/button";
import {NumberInput} from "./activity/NumberInput";
export function SetArrayInput({value,onChange}:{value:SetEntry[];onChange:(next:SetEntry[])=>void}){
 function update(index:number,patch:Partial<SetEntry>){onChange(value.map((s,i)=>i===index?{...s,...patch}:s));}
 return <div className="space-y-3">{value.map((s,i)=><div key={i} className="space-y-3 rounded-xl border bg-background/40 p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium">Serija {i+1}</span><div className="flex items-center gap-2"><select aria-label={`Način unosa serije ${i+1}`} className="h-8 max-w-40 rounded-md border bg-background px-2 text-xs" value={s.durationSec!=null?"time":"reps"} onChange={e=>update(i,e.target.value==="time"?{durationSec:0,reps:undefined}:{reps:0,durationSec:undefined})}><option value="reps">Ponavljanja</option><option value="time">Na vreme</option></select><Button type="button" size="icon" variant="ghost" aria-label={`Ukloni seriju ${i+1}`} onClick={()=>onChange(value.filter((_,index)=>index!==i))}><Trash2 className="size-4"/></Button></div></div><div className="grid grid-cols-2 gap-3"><NumberInput key={`${i}-${s.durationSec!=null?"time":"reps"}`} label={s.durationSec!=null?"Trajanje":"Ponavljanja"} unit={s.durationSec!=null?"s":undefined} integer min={1} value={(s.durationSec??s.reps)||null} onChange={n=>update(i,s.durationSec!=null?{durationSec:n??0}:{reps:n??0})}/><NumberInput label={s.bodyweight?"Dodatna težina":"Težina"} unit="kg" value={s.weight} onChange={n=>update(i,{weight:n??undefined})}/></div><div className="flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground">{([{key:"bodyweight",label:"Sopstvena težina"},{key:"warmup",label:"Zagrevanje"},{key:"perSide",label:"Po strani"}] as const).map(f=><label key={f.key} className="flex items-center gap-2"><input type="checkbox" checked={s[f.key]??false} onChange={e=>update(i,{[f.key]:e.target.checked})}/>{f.label}</label>)}</div></div>)}<Button type="button" size="sm" variant="outline" onClick={()=>onChange([...value,{reps:0}])}><Plus className="mr-2 size-4"/>Dodaj seriju</Button></div>;
}
