"use client";
import {describeBlock} from "@/lib/physical/display";
import {useState} from "react";
import {ChevronDown,ArrowUp,ArrowDown,Copy,Trash2,Footprints,Dumbbell,Zap} from "lucide-react";
import type {TrainingBlock} from "@/lib/physical/types";
import {Button} from "@/components/ui/button";
const labels={split:"Trčanje",exercise:"Vežba",sprint:"Sprintovi / intervali"};
const icons={split:Footprints,exercise:Dumbbell,sprint:Zap};
export function BlockCard({block,index,count,onMove,onRemove,onDuplicate,children,error,title}:{block:TrainingBlock;index:number;count:number;onMove:(dir:-1|1)=>void;onRemove:()=>void;onDuplicate:()=>void;children:React.ReactNode;error?:string;title?:string}){
 const [collapsed,setCollapsed]=useState(false),Icon=icons[block.kind];
 return <section data-block={block.rowKey} className={`min-w-0 overflow-hidden rounded-2xl border bg-card shadow-sm ${error?"border-destructive":""}`}><div className="flex flex-wrap items-center justify-between gap-2 border-b bg-muted/20 px-4 py-3"><button type="button" className="flex min-w-0 items-center gap-3 text-left" aria-expanded={!collapsed||!!error} onClick={()=>setCollapsed(!collapsed)}><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4"/></span><span className="min-w-0"><span className="block text-xs text-muted-foreground">Deo {index+1}</span><span className="block break-words text-sm font-semibold">{block.details.label||title||labels[block.kind]}</span></span><ChevronDown className={`size-4 shrink-0 transition-transform ${collapsed?"-rotate-90":""}`}/></button><div className="flex items-center gap-1"><Button type="button" variant="ghost" size="icon" aria-label={`Pomeri deo ${index+1} gore`} disabled={index===0} onClick={()=>onMove(-1)}><ArrowUp className="size-4"/></Button><Button type="button" variant="ghost" size="icon" aria-label={`Pomeri deo ${index+1} dole`} disabled={index===count-1} onClick={()=>onMove(1)}><ArrowDown className="size-4"/></Button><Button type="button" variant="ghost" size="icon" aria-label={`Dupliraj deo ${index+1}`} onClick={onDuplicate}><Copy className="size-4"/></Button><Button type="button" variant="ghost" size="icon" aria-label={`Ukloni deo ${index+1}`} onClick={onRemove}><Trash2 className="size-4"/></Button></div></div><div hidden={collapsed&&!error} className="space-y-5 p-4 sm:p-5">{children}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</div>{collapsed&&!error&&<div className="flex items-center justify-between px-4 py-3 text-xs text-muted-foreground"><span>{block.details.status==="done"?"Urađeno":block.details.status==="skipped"?"Preskočeno":"Za unos"}</span><span className="ml-3 text-right">{describeBlock(block)}</span></div>}</section>;
}
