"use client";
import type {Exercise,ExerciseGroup,PhysicalField} from "@/db/schema/physical";
import {Textarea} from "@/components/ui/textarea";
import {NumberInput} from "./NumberInput";
import {DurationFields} from "./DurationFields";
import {SetArrayInput} from "../SetArrayInput";
import type {SetEntry} from "@/lib/physical/types";
export function CustomFields({fields,values,onChange,groups,exercises,exclude=[]}:{fields:PhysicalField[];values:Record<string,unknown>;onChange:(values:Record<string,unknown>)=>void;groups:ExerciseGroup[];exercises:Exercise[];exclude?:string[]}){
 const extra=fields.filter(f=>!exclude.includes(f.key)),known=new Set([...fields.map(f=>f.key),...exclude]),unknown=Object.entries(values).filter(([key,value])=>!known.has(key)&&value!=null);
 function set(key:string,value:unknown){onChange({...values,[key]:value});}
 return <div className="space-y-4">{extra.map(f=>{const value=values[f.key];switch(f.kind){case "text":return <label key={f.key} className="block space-y-2 text-sm">{f.label}<Textarea value={typeof value==="string"?value:""} onChange={e=>set(f.key,e.target.value||null)}/></label>;case "number":case "decimal":case "distance_km":return <NumberInput key={f.key} label={f.label} value={value as number|null} integer={f.kind==="number"} onChange={n=>set(f.key,n)}/>;case "duration_sec":return <DurationFields key={f.key} label={f.label} value={value as number|null} onChange={n=>set(f.key,n)}/>;case "sets_array":return <fieldset key={f.key}><legend>{f.label}</legend><SetArrayInput value={(value as SetEntry[])??[]} onChange={sets=>set(f.key,sets)}/></fieldset>;case "category_ref":case "exercise_ref":{const options=f.kind==="category_ref"?groups:exercises;return <label key={f.key} className="block text-sm">{f.label}<select className="mt-2 h-10 w-full rounded-md border bg-background px-2" value={typeof value==="string"?value:""} onChange={e=>set(f.key,e.target.value||null)}><option value="">Bez izbora</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;}}})}{unknown.length>0&&<details><summary className="cursor-pointer text-xs text-muted-foreground">Ranije sačuvani dodatni podaci</summary><dl className="mt-2 space-y-2 text-xs">{unknown.map(([key,value])=><div key={key}><dt className="font-medium">{key}</dt><dd className="break-words text-muted-foreground">{JSON.stringify(value)}</dd></div>)}</dl></details>}</div>;
}
