"use client";
import {useState} from "react";
import {ArrowDown,ArrowUp,Plus,Trash2} from "lucide-react";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
import {NumberInput} from "./NumberInput";
import {intervalSeconds,intervalTotals,parseMinutesSeconds,progressionExample,type IntervalSegment} from "@/lib/physical/intervals";
import {secondsToMmSs} from "@/lib/physical/formatDuration";
const usesPace=(s:IntervalSegment)=>(s.timeMode??(s.pace!=null?"pace":"duration"))==="pace";
export function IntervalFields({segments,onChange}:{segments:IntervalSegment[];onChange:(segments:IntervalSegment[])=>void}){
 const update=(i:number,s:IntervalSegment)=>onChange(segments.map((old,index)=>index===i?s:old));
 const totals=intervalTotals(segments);
 return <div className="space-y-4"><p className="text-sm text-muted-foreground">Unesi deonice redom. Za svaku izaberi tempo ili ukupno trajanje.</p>{segments.map((s,i)=><section key={i} className="space-y-3 rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium">Deonica {i+1}</span><div className="flex gap-1">{([-1,1] as const).map(dir=><Button key={dir} type="button" size="icon" variant="ghost" aria-label={`Pomeri deonicu ${i+1} ${dir===-1?"gore":"dole"}`} disabled={i+dir<0||i+dir>=segments.length} onClick={()=>{const next=[...segments];[next[i],next[i+dir]]=[next[i+dir],next[i]];onChange(next);}}>{dir===-1?<ArrowUp className="size-4"/>:<ArrowDown className="size-4"/>}</Button>)}<Button type="button" size="icon" variant="ghost" aria-label={`Ukloni deonicu ${i+1}`} onClick={()=>onChange(segments.filter((_,index)=>index!==i))}><Trash2 className="size-4"/></Button></div></div><label className="block space-y-2 text-sm">Naziv deonice<Input aria-label={`Naziv deonice ${i+1}`} value={s.label} placeholder="Zagrevanje, tempo, oporavak, rastrčavanje…" onChange={e=>update(i,{...s,label:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-3 sm:items-end"><NumberInput label={`Distanca deonice ${i+1}`} unit="km" min={0.001} value={s.distance} onChange={distance=>update(i,{...s,distance})}/><label className="block space-y-2 text-sm">Unos vremena<select aria-label={`Unos vremena deonice ${i+1}`} className="h-12 w-full" value={usesPace(s)?"pace":"duration"} onChange={e=>update(i,{...s,timeMode:e.target.value as "pace"|"duration",duration:e.target.value==="duration"?(intervalSeconds(s)??null):null,pace:e.target.value==="pace"?(s.distance&&s.duration?Math.round(s.duration/s.distance):300):null})}><option value="duration">Trajanje</option><option value="pace">Tempo /km</option></select></label><MinutesSeconds key={`${i}-${usesPace(s)?"pace":"duration"}`} label={usesPace(s)?`Tempo deonice ${i+1} (min:sek /km)`:`Trajanje deonice ${i+1} (min:sek)`} value={s.pace??s.duration} onChange={n=>update(i,usesPace(s)?{...s,timeMode:"pace",pace:n}:{...s,duration:n})}/></div>{usesPace(s)&&intervalSeconds(s)!=null&&<p className="text-xs text-muted-foreground">Trajanje deonice: {secondsToMmSs(intervalSeconds(s)!)}</p>}</section>)}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={()=>onChange([...segments,{label:"",distance:null,duration:null,pace:null}])}><Plus className="mr-2 size-4"/>Dodaj deonicu</Button>{segments.length===0&&<Button type="button" variant="outline" size="sm" onClick={()=>onChange(progressionExample())}>Primer: 3 × 1 km progresivno</Button>}</div>{segments.length>0&&<p className="text-sm font-medium">Ukupno: {new Intl.NumberFormat("sr-RS").format(totals.distance)} km · {secondsToMmSs(totals.duration)}{!totals.distanceComplete||!totals.timeComplete?" · dopuni deonice":""}</p>}</div>;
}
function MinutesSeconds({label,value,onChange}:{label:string;value:number|null;onChange:(n:number|null)=>void}){
 const [text,setText]=useState(value==null?"":secondsToMmSs(value)),[last,setLast]=useState(value),[error,setError]=useState(false);
 if(last!==value){setLast(value);setText(value==null?"":secondsToMmSs(value));setError(false);}
 return <label className="block space-y-2 text-sm">{label}<Input aria-label={label} placeholder="7:00" inputMode="text" value={text} className="h-12 text-lg tabular-nums" aria-invalid={error} ref={el=>el?.setCustomValidity(error?"Unesi vreme kao min:sek, na primer 4:50.":"")} onChange={e=>{setText(e.target.value);const n=parseMinutesSeconds(e.target.value),invalid=!!e.target.value.trim()&&n==null;setError(invalid);e.target.setCustomValidity(invalid?"Unesi vreme kao min:sek, na primer 4:50.":"");if(!invalid){setLast(n);onChange(n);}}}/>{error&&<span className="text-xs text-destructive">Koristi min:sek, npr. 4:50.</span>}</label>;
}
