import type { NodePgDatabase } from "drizzle-orm/node-postgres";

import * as schema from "./schema";
import {
  accounts,
  currencies,
  instruments,
} from "./schema";

type SeedDatabase = NodePgDatabase<typeof schema>;

type CatalogCurrency = typeof currencies.$inferInsert;

const activeCurrencyCodes = new Set(["RSD", "EUR", "USD", "HUF"]);

const catalogCurrencies: CatalogCurrency[] = [
  { code: "AED", name: "UAE dirham", minorUnit: "2" },
  { code: "AFN", name: "Afghan afghani", minorUnit: "2" },
  { code: "ALL", name: "Albanian lek", minorUnit: "2" },
  { code: "AMD", name: "Armenian dram", minorUnit: "2" },
  { code: "ANG", name: "Netherlands Antillean guilder", minorUnit: "2" },
  { code: "AOA", name: "Angolan kwanza", minorUnit: "2" },
  { code: "ARS", name: "Argentine peso", minorUnit: "2" },
  { code: "AUD", name: "Australian dollar", minorUnit: "2" },
  { code: "AWG", name: "Aruban florin", minorUnit: "2" },
  { code: "AZN", name: "Azerbaijan manat", minorUnit: "2" },
  { code: "BAM", name: "Bosnia and Herzegovina convertible mark", minorUnit: "2" },
  { code: "BBD", name: "Barbados dollar", minorUnit: "2" },
  { code: "BDT", name: "Bangladeshi taka", minorUnit: "2" },
  { code: "BGN", name: "Bulgarian lev", minorUnit: "2" },
  { code: "BHD", name: "Bahraini dinar", minorUnit: "3" },
  { code: "BIF", name: "Burundi franc", minorUnit: "0" },
  { code: "BMD", name: "Bermudian dollar", minorUnit: "2" },
  { code: "BND", name: "Brunei dollar", minorUnit: "2" },
  { code: "BOB", name: "Boliviano", minorUnit: "2" },
  { code: "BOV", name: "Bolivian Mvdol", minorUnit: "2" },
  { code: "BRL", name: "Brazilian real", minorUnit: "2" },
  { code: "BSD", name: "Bahamian dollar", minorUnit: "2" },
  { code: "BTN", name: "Bhutanese ngultrum", minorUnit: "2" },
  { code: "BWP", name: "Botswana pula", minorUnit: "2" },
  { code: "BYN", name: "Belarusian ruble", minorUnit: "2" },
  { code: "BZD", name: "Belize dollar", minorUnit: "2" },
  { code: "CAD", name: "Canadian dollar", minorUnit: "2" },
  { code: "CDF", name: "Congolese franc", minorUnit: "2" },
  { code: "CHE", name: "WIR euro", minorUnit: "2" },
  { code: "CHF", name: "Swiss franc", minorUnit: "2" },
  { code: "CHW", name: "WIR franc", minorUnit: "2" },
  { code: "CLF", name: "Unidad de Fomento", minorUnit: "4" },
  { code: "CLP", name: "Chilean peso", minorUnit: "0" },
  { code: "CNY", name: "Yuan renminbi", minorUnit: "2" },
  { code: "COP", name: "Colombian peso", minorUnit: "2" },
  { code: "COU", name: "Unidad de Valor Real", minorUnit: "2" },
  { code: "CRC", name: "Costa Rican colon", minorUnit: "2" },
  { code: "CUP", name: "Cuban peso", minorUnit: "2" },
  { code: "CVE", name: "Cabo Verde escudo", minorUnit: "2" },
  { code: "CZK", name: "Czech koruna", minorUnit: "2" },
  { code: "DJF", name: "Djibouti franc", minorUnit: "0" },
  { code: "DKK", name: "Danish krone", minorUnit: "2" },
  { code: "DOP", name: "Dominican peso", minorUnit: "2" },
  { code: "DZD", name: "Algerian dinar", minorUnit: "2" },
  { code: "EGP", name: "Egyptian pound", minorUnit: "2" },
  { code: "ERN", name: "Eritrean nakfa", minorUnit: "2" },
  { code: "ETB", name: "Ethiopian birr", minorUnit: "2" },
  { code: "RSD", name: "Serbian dinar", minorUnit: "2", isActive: true },
  { code: "EUR", name: "Euro", minorUnit: "2", isActive: true },
  { code: "FJD", name: "Fiji dollar", minorUnit: "2" },
  { code: "FKP", name: "Falkland Islands pound", minorUnit: "2" },
  { code: "GBP", name: "Pound sterling", minorUnit: "2" },
  { code: "GEL", name: "Georgian lari", minorUnit: "2" },
  { code: "GHS", name: "Ghana cedi", minorUnit: "2" },
  { code: "GIP", name: "Gibraltar pound", minorUnit: "2" },
  { code: "GMD", name: "Gambian dalasi", minorUnit: "2" },
  { code: "GNF", name: "Guinean franc", minorUnit: "0" },
  { code: "GTQ", name: "Guatemalan quetzal", minorUnit: "2" },
  { code: "GYD", name: "Guyana dollar", minorUnit: "2" },
  { code: "HKD", name: "Hong Kong dollar", minorUnit: "2" },
  { code: "HNL", name: "Honduran lempira", minorUnit: "2" },
  { code: "HTG", name: "Haitian gourde", minorUnit: "2" },
  { code: "HUF", name: "Hungarian forint", minorUnit: "2", isActive: true },
  { code: "IDR", name: "Indonesian rupiah", minorUnit: "2" },
  { code: "ILS", name: "New Israeli sheqel", minorUnit: "2" },
  { code: "INR", name: "Indian rupee", minorUnit: "2" },
  { code: "IQD", name: "Iraqi dinar", minorUnit: "3" },
  { code: "IRR", name: "Iranian rial", minorUnit: "2" },
  { code: "ISK", name: "Iceland krona", minorUnit: "0" },
  { code: "JMD", name: "Jamaican dollar", minorUnit: "2" },
  { code: "JOD", name: "Jordanian dinar", minorUnit: "3" },
  { code: "JPY", name: "Japanese yen", minorUnit: "0" },
  { code: "KES", name: "Kenyan shilling", minorUnit: "2" },
  { code: "KGS", name: "Kyrgyzstani som", minorUnit: "2" },
  { code: "KHR", name: "Cambodian riel", minorUnit: "2" },
  { code: "KMF", name: "Comorian franc", minorUnit: "0" },
  { code: "KPW", name: "North Korean won", minorUnit: "2" },
  { code: "KRW", name: "Won", minorUnit: "0" },
  { code: "KWD", name: "Kuwaiti dinar", minorUnit: "3" },
  { code: "KYD", name: "Cayman Islands dollar", minorUnit: "2" },
  { code: "KZT", name: "Kazakhstani tenge", minorUnit: "2" },
  { code: "LAK", name: "Lao kip", minorUnit: "2" },
  { code: "LBP", name: "Lebanese pound", minorUnit: "2" },
  { code: "LKR", name: "Sri Lanka rupee", minorUnit: "2" },
  { code: "LRD", name: "Liberian dollar", minorUnit: "2" },
  { code: "LSL", name: "Lesotho loti", minorUnit: "2" },
  { code: "LYD", name: "Libyan dinar", minorUnit: "3" },
  { code: "MAD", name: "Moroccan dirham", minorUnit: "2" },
  { code: "MDL", name: "Moldovan leu", minorUnit: "2" },
  { code: "MGA", name: "Malagasy ariary", minorUnit: "2" },
  { code: "MKD", name: "Denar", minorUnit: "2" },
  { code: "MMK", name: "Myanmar kyat", minorUnit: "2" },
  { code: "MNT", name: "Mongolian tugrik", minorUnit: "2" },
  { code: "MOP", name: "Macanese pataca", minorUnit: "2" },
  { code: "MRU", name: "Mauritanian ouguiya", minorUnit: "2" },
  { code: "MUR", name: "Mauritius rupee", minorUnit: "2" },
  { code: "MVR", name: "Maldivian rufiyaa", minorUnit: "2" },
  { code: "MWK", name: "Malawi kwacha", minorUnit: "2" },
  { code: "MXN", name: "Mexican peso", minorUnit: "2" },
  { code: "MXV", name: "Mexican Unidad de Inversion", minorUnit: "2" },
  { code: "MYR", name: "Malaysian ringgit", minorUnit: "2" },
  { code: "MZN", name: "Mozambique metical", minorUnit: "2" },
  { code: "NAD", name: "Namibia dollar", minorUnit: "2" },
  { code: "NGN", name: "Nigerian naira", minorUnit: "2" },
  { code: "NIO", name: "Nicaraguan cordoba oro", minorUnit: "2" },
  { code: "NOK", name: "Norwegian krone", minorUnit: "2" },
  { code: "NPR", name: "Nepalese rupee", minorUnit: "2" },
  { code: "NZD", name: "New Zealand dollar", minorUnit: "2" },
  { code: "OMR", name: "Rial Omani", minorUnit: "3" },
  { code: "PAB", name: "Panamanian balboa", minorUnit: "2" },
  { code: "PEN", name: "Sol", minorUnit: "2" },
  { code: "PGK", name: "Papua New Guinean kina", minorUnit: "2" },
  { code: "PHP", name: "Philippine peso", minorUnit: "2" },
  { code: "PKR", name: "Pakistan rupee", minorUnit: "2" },
  { code: "PLN", name: "Polish zloty", minorUnit: "2" },
  { code: "PYG", name: "Paraguayan guarani", minorUnit: "0" },
  { code: "QAR", name: "Qatari riyal", minorUnit: "2" },
  { code: "RON", name: "Romanian leu", minorUnit: "2" },
  { code: "RUB", name: "Russian ruble", minorUnit: "2" },
  { code: "RWF", name: "Rwanda franc", minorUnit: "0" },
  { code: "SAR", name: "Saudi riyal", minorUnit: "2" },
  { code: "SBD", name: "Solomon Islands dollar", minorUnit: "2" },
  { code: "SCR", name: "Seychelles rupee", minorUnit: "2" },
  { code: "SDG", name: "Sudanese pound", minorUnit: "2" },
  { code: "SEK", name: "Swedish krona", minorUnit: "2" },
  { code: "SGD", name: "Singapore dollar", minorUnit: "2" },
  { code: "SHP", name: "Saint Helena pound", minorUnit: "2" },
  { code: "SLE", name: "Leone", minorUnit: "2" },
  { code: "SLL", name: "Leone", minorUnit: "2" },
  { code: "SOS", name: "Somali shilling", minorUnit: "2" },
  { code: "SRD", name: "Surinam dollar", minorUnit: "2" },
  { code: "SSP", name: "South Sudanese pound", minorUnit: "2" },
  { code: "STN", name: "Dobra", minorUnit: "2" },
  { code: "SVC", name: "El Salvador colon", minorUnit: "2" },
  { code: "SYP", name: "Syrian pound", minorUnit: "2" },
  { code: "SZL", name: "Lilangeni", minorUnit: "2" },
  { code: "THB", name: "Thai baht", minorUnit: "2" },
  { code: "TJS", name: "Tajikistani somoni", minorUnit: "2" },
  { code: "TMT", name: "Turkmenistan new manat", minorUnit: "2" },
  { code: "TND", name: "Tunisian dinar", minorUnit: "3" },
  { code: "TOP", name: "Tongan pa'anga", minorUnit: "2" },
  { code: "TRY", name: "Turkish lira", minorUnit: "2" },
  { code: "TTD", name: "Trinidad and Tobago dollar", minorUnit: "2" },
  { code: "TWD", name: "New Taiwan dollar", minorUnit: "2" },
  { code: "TZS", name: "Tanzanian shilling", minorUnit: "2" },
  { code: "UAH", name: "Ukrainian hryvnia", minorUnit: "2" },
  { code: "UGX", name: "Uganda shilling", minorUnit: "0" },
  { code: "USD", name: "United States dollar", minorUnit: "2", isActive: true },
  { code: "USN", name: "US dollar next day", minorUnit: "2" },
  { code: "UYI", name: "Uruguay Peso en Unidades Indexadas", minorUnit: "0" },
  { code: "UYU", name: "Peso Uruguayo", minorUnit: "2" },
  { code: "UYW", name: "Unidad Previsional", minorUnit: "4" },
  { code: "UZS", name: "Uzbekistan sum", minorUnit: "2" },
  { code: "VED", name: "Bolivar Soberano", minorUnit: "2" },
  { code: "VES", name: "Bolivar Soberano", minorUnit: "2" },
  { code: "VND", name: "Dong", minorUnit: "0" },
  { code: "VUV", name: "Vatu", minorUnit: "0" },
  { code: "WST", name: "Tala", minorUnit: "2" },
  { code: "XAF", name: "CFA franc BEAC", minorUnit: "0" },
  { code: "XAG", name: "Silver", minorUnit: "N.A." },
  { code: "XAU", name: "Gold", minorUnit: "N.A." },
  { code: "XBA", name: "Bond Markets Unit European Composite Unit", minorUnit: "N.A." },
  { code: "XBB", name: "Bond Markets Unit European Monetary Unit", minorUnit: "N.A." },
  { code: "XBC", name: "Bond Markets Unit European Unit of Account 9", minorUnit: "N.A." },
  { code: "XBD", name: "Bond Markets Unit European Unit of Account 17", minorUnit: "N.A." },
  { code: "XCD", name: "East Caribbean dollar", minorUnit: "2" },
  { code: "XCG", name: "Caribbean guilder", minorUnit: "2" },
  { code: "XDR", name: "SDR", minorUnit: "N.A." },
  { code: "XOF", name: "CFA franc BCEAO", minorUnit: "0" },
  { code: "XPD", name: "Palladium", minorUnit: "N.A." },
  { code: "XPF", name: "CFP franc", minorUnit: "0" },
  { code: "XPT", name: "Platinum", minorUnit: "N.A." },
  { code: "XSU", name: "Sucre", minorUnit: "N.A." },
  { code: "XTS", name: "Codes reserved for testing", minorUnit: "N.A." },
  { code: "XUA", name: "ADB Unit of Account", minorUnit: "N.A." },
  { code: "XXX", name: "No currency", minorUnit: "N.A." },
  { code: "YER", name: "Yemeni rial", minorUnit: "2" },
  { code: "ZAR", name: "South African rand", minorUnit: "2" },
  { code: "ZMW", name: "Zambian kwacha", minorUnit: "2" },
  { code: "ZWG", name: "Zimbabwe Gold", minorUnit: "2" },
];

const seedAccounts: (typeof accounts.$inferInsert)[] = [
  {
    id: "system-equity",
    name: "System equity",
    classification: "equity",
    subtype: "opening_balance",
    currencyCode: "EUR",
    isSystem: true,
  },
  {
    id: "system-income",
    name: "System income",
    classification: "income",
    subtype: "income",
    currencyCode: "EUR",
    isSystem: true,
  },
  {
    id: "system-expense",
    name: "System expense",
    classification: "expense",
    subtype: "expense",
    currencyCode: "EUR",
    isSystem: true,
  },
  {
    id: "system-fx",
    name: "System foreign exchange",
    classification: "equity",
    subtype: "foreign_exchange",
    currencyCode: "EUR",
    isSystem: true,
  },
  {
    id: "system-fees",
    name: "System fees",
    classification: "expense",
    subtype: "fees",
    currencyCode: "EUR",
    isSystem: true,
  },
  {
    id: "receivable-rsd",
    name: "Dugovanja prema meni — RSD",
    classification: "receivable",
    subtype: "personal_receivable",
    currencyCode: "RSD",
    isSystem: false,
  },
  {
    id: "receivable-eur",
    name: "Dugovanja prema meni — EUR",
    classification: "receivable",
    subtype: "personal_receivable",
    currencyCode: "EUR",
    isSystem: false,
  },
];

const seedInstruments: (typeof instruments.$inferInsert)[] = [
  {
    id: "instrument-btc",
    symbol: "BTC",
    name: "Bitcoin",
    class: "crypto",
    valuationMethod: "market_quote",
    quoteCurrencyCode: "EUR",
    provider: "coingecko",
    providerId: "bitcoin",
  },
  {
    id: "instrument-eth",
    symbol: "ETH",
    name: "Ethereum",
    class: "crypto",
    valuationMethod: "market_quote",
    quoteCurrencyCode: "EUR",
    provider: "coingecko",
    providerId: "ethereum",
  },
  {
    id: "instrument-vwce",
    symbol: "VWCE",
    name: "Vanguard FTSE All-World UCITS ETF (USD) Accumulating",
    class: "etf",
    valuationMethod: "market_quote",
    quoteCurrencyCode: "EUR",
    provider: "alpha_vantage",
    isin: "IE00BK5BQT80",
    exchange: "Deutsche Börse/Xetra",
  },
  {
    id: "instrument-googl",
    symbol: "GOOGL",
    name: "Alphabet Inc. Class A",
    class: "stock",
    valuationMethod: "market_quote",
    quoteCurrencyCode: "USD",
    provider: "alpha_vantage",
    providerId: "GOOGL",
    exchange: "Nasdaq",
  },
  {
    id: "instrument-amd",
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc. common stock",
    class: "stock",
    valuationMethod: "market_quote",
    quoteCurrencyCode: "USD",
    provider: "alpha_vantage",
    providerId: "AMD",
    exchange: "Nasdaq",
  },
];

export async function seedDatabase(database: SeedDatabase): Promise<void> {
  await database.transaction(async (tx) => {
    await tx
      .insert(currencies)
      .values(
        catalogCurrencies.map((currency) => ({
          ...currency,
          isActive: activeCurrencyCodes.has(currency.code),
          activatedAt: activeCurrencyCodes.has(currency.code)
            ? new Date("2026-08-22T00:00:00.000Z")
            : null,
        })),
      )
      .onConflictDoNothing();

    await tx.insert(accounts).values(seedAccounts).onConflictDoNothing();

    await tx
      .insert(instruments)
      .values(seedInstruments)
      .onConflictDoNothing();
  });
}
